[versions]
asm = "9.4"      # https://asm.ow2.io/versions.html
gson = "2.10.1"   # https://github.com/google/gson/releases
lombok = "1.18.22"  # https://projectlombok.org/download
junit = "5.8.1"    # https://github.com/junit-team/junit5/releases

[libraries]
asm         = { module = "org.ow2.asm:asm",                        version.ref = "asm"       }
asmtree     = { module = "org.ow2.asm:asm-tree",                   version.ref = "asm"       }
asmcommons  = { module = "org.ow2.asm:asm-commons",                version.ref = "asm"       }
gson        = { module = "com.google.code.gson:gson",              version.ref = "gson"      }
lombok      = { module = "org.projectlombok:lombok",               version.ref = "lombok"    }
junitapi    = { module = "org.junit.jupiter:junit-jupiter-api",    version.ref = "junit"     }
junitengine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit"     }
